1. Загрузка JSON

In [1]:
import json
import pandas as pd

FILE_NAME = "raw_20260305_102335"
with open(f"../data/raw/variant_09/{FILE_NAME}.json") as f:
    data = json.load(f)

2. Проверка структуры

In [2]:
type(data)

list

In [3]:
len(data)

2

In [4]:
type(data[0])

dict

In [5]:
type(data[1])

list

3. Построение DataFrame

In [6]:
df = pd.json_normalize(data[1])

4. Проверка таблицы

In [7]:
df.head()

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,RUS,2025,NaN,,,0,NY.GDP.MKTP.CD,GDP (current US$),RU,Russian Federation
1,RUS,2024,2.173836e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),RU,Russian Federation
2,RUS,2023,2.071506e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),RU,Russian Federation
3,RUS,2022,2.291612e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),RU,Russian Federation
4,RUS,2021,1.829187e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),RU,Russian Federation

In [8]:
df.shape

(66, 10)

In [9]:
df.columns

Index(['countryiso3code', 'date', 'value', 'unit', 'obs_status', 'decimal',
       'indicator.id', 'indicator.value', 'country.id', 'country.value'],
      dtype='object')

In [10]:
df.dtypes

countryiso3code     object
date                object
value              float64
unit                object
obs_status          object
decimal              int64
indicator.id        object
indicator.value     object
country.id          object
country.value       object
dtype: object

5. Очистка данных

In [11]:
df = df[
    [
        "date",
        "value",
        "countryiso3code",
        "indicator.id"
    ]
]

df = df.rename(columns={
    "date": "year",
    "countryiso3code": "country_iso3",
    "indicator.id": "indicator"
})

df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")
df["value"] = pd.to_numeric(df["value"], errors="coerce")

df = df.drop_duplicates()

6. Проверка после очистки

In [12]:
df.head()

   year         value country_iso3       indicator
0  2025           NaN          RUS  NY.GDP.MKTP.CD
1  2024  2.173836e+12          RUS  NY.GDP.MKTP.CD
2  2023  2.071506e+12          RUS  NY.GDP.MKTP.CD
3  2022  2.291612e+12          RUS  NY.GDP.MKTP.CD
4  2021  1.829187e+12          RUS  NY.GDP.MKTP.CD

In [13]:
df.dtypes

year              Int64
value           float64
country_iso3     object
indicator        object
dtype: object

In [14]:
df.isna().sum()

year             0
value           29
country_iso3     0
indicator        0
dtype: int64

In [15]:
df.shape

(66, 4)

7. Сохранение normalized CSV

In [16]:
df.to_csv(
    f"../data/normalized/variant_09/normalized{FILE_NAME[3:]}.csv",
    index=False
)